import '@/styles/globals.css';
import { Montserrat } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import { ThemeProvider } from '@/components/ThemeProvider';
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'krivtsoff.develop()',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon.ico?v-4'],
    apple: ['/apple-touch-icon.png?v-4'],
    shortcut: ['/apple-touch-icon.png?v-4']
  },
  manifest: '/site.webmanifest'
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={montserrat.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
